# Generated by Django 4.1.5 on 2023-01-03 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('v0', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='sensor_id')),
                ('v18', models.FloatField(verbose_name='dwell_time')),
                ('Time', models.DateTimeField()),
            ],
        ),
    ]
